config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'public/users/sessions',
    registrations: 'public/users/registrations'
  }

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    resources :stages, except: [:destroy] do
      resource :bookmarks, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update] do
      member do
        get 'quit'
        patch 'withdraw'
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :reviews do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    get 'search' => 'stages#search'

    resources :contacts, only: [:new, :create]
    post 'contacts/confirm' => 'contacts#confirm'
    post 'contacts/back' => 'contacts#back'
    get 'contacts/done' => 'contacts#done'

    devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    end
  end

  # 以下管理者のルーティング
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :stages
    resources :users, only: [:index, :edit, :update]
    resources :reviews, only: [:index, :show, :edit, :update, :destroy]
    get 'search' => 'search#search'
    resources :contacts, only: [:index, :show]
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :stages
  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    unless @genre.save
      flash[:alert] = "ジャンルを入力してください"
    end
    redirect_to request.referer
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      flash.now[:alert] = "ジャンルを入力してください"
      render 'edit'
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class='container'>
  <h2 class='page-title'>ジャンル編集</h2>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 mx-auto">
      <%= form_with model: @genre, url: admin_genre_path, local: true do |f| %>
          <div class="form-group col-10 mx-auto">
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group text-center">
            <%= f.submit "変更を保存", class: 'btn btn-dark ml-3' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class='container'>
  <h2 class='page-title'>ジャンル一覧・追加</h2>
  <%= render 'layouts/errors', obj: @genre %>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 mx-auto">
      <%= form_with model: @genre, url: admin_genres_path, local: true do |f| %>
        <div class="form-group col-10 mx-auto">
          <%= f.text_field :name, :placeholder => "ジャンル名", class: "form-control" %>
        </div>
        <div class="form-group text-center">
          <%= f.submit "新規登録", class: 'btn btn-dark ml-2' %>
        </div>
      <% end %>
    </div>
  </div>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-4 pt-4 mx-auto">
      <table class="table bg-white">
        <thead class="thead-light">
          <tr>
            <th>ジャンル名</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
            <tr>
              <td><%= link_to genre.name, admin_stages_path(genre_id: genre.id), class: "text-decoration-underline" %></td>
              <td><%= link_to "編集する", edit_admin_genre_path(genre), class: "btn btn-sm btn-outline-dark" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      </div>
    </div>
  </div>
</div>