config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'public/users/sessions',
    registrations: 'public/users/registrations'
  }

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    resources :stages, except: [:destroy] do
      resource :bookmarks, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update] do
      member do
        get 'quit'
        patch 'withdraw'
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :reviews do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    get 'search' => 'stages#search'

    resources :contacts, only: [:new, :create]
    post 'contacts/confirm' => 'contacts#confirm'
    post 'contacts/back' => 'contacts#back'
    get 'contacts/done' => 'contacts#done'

    devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    end
  end

  # 以下管理者のルーティング
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :stages
    resources :users, only: [:index, :edit, :update]
    resources :reviews, only: [:index, :show, :edit, :update, :destroy]
    get 'search' => 'search#search'
    resources :contacts, only: [:index, :show]
  end
end

app/models/stage.rb
class Stage < ApplicationRecord
  belongs_to :genre
  has_many :reviews, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :genre, :start_date, :end_date, presence: true
  validate :end_date_check

  def end_date_check
    errors.add(:end_date, "は公演開始日と同じ日または遅い日を選択してください") if start_date.present? && end_date.present? && self.start_date > self.end_date
  end

  def bookmarked_by?(user)
    bookmarks.where(user_id: user).exists?
  end

  def stage_id_and_name
    self.id.to_s + '. ' + self.name
  end

  scope :stages_now, -> { where("start_date <= ?", Date.today).where("end_date >= ?", Date.today) }
  scope :stages_coming, -> { where("start_date > ?", Date.today) }
end

app/controllers/admin/stages_controller.rb
class Admin::StagesController < ApplicationController
  before_action :authenticate_admin!
  def index
    if params[:genre_id]
      @genre = Genre.find(params[:genre_id])
      @stages = Stage.where(genre_id: params[:genre_id]).order(start_date: :desc).page(params[:page]).per(10)
    else
      @stages = Stage.all.order(start_date: :desc).page(params[:page]).per(10)
    end
  end

  def new
    @stage = Stage.new
  end

  def create
    @stage = Stage.new(stage_params)
    if @stage.save
      redirect_to admin_stage_path(@stage)
    else
      render "admin/stages/new"
    end
  end

  def show
    @stage = Stage.find(params[:id])
  end

  def edit
    @stage = Stage.find(params[:id])
  end

  def update
    @stage = Stage.find(params[:id])
    if @stage.update(stage_params)
      redirect_to admin_stage_path
    else
      render "admin/stages/edit"
    end
  end

  def destroy
    Stage.find(params[:id]).destroy
    redirect_to admin_stages_path
  end

  private

  def stage_params
    params.require(:stage).permit(:name, :genre_id, :start_date, :end_date, :detail)
  end
end

app/helpers/admin/stages_helper.rb
module Admin::StagesHelper
end

app/views/admin/stages/_index.html.erb
<div class="table-responsive">
  <table class="table bg-white text-center" style="table-layout:fixed;">
    <thead class="thead-light">
      <tr>
        <th style="width:400px;">公演名</th>
        <th style="width:100px;">評価</th>
        <th style="width:150px;">レビュー数</th>
      </tr>
    </thead>
    <tbody>
      <% stages.each do |stage| %>
        <tr>
          <td class="text-left ml-3"><%= link_to stage.name, admin_stage_path(stage), class: "text-decoration-underline"%></td>
          <td><%= stage.reviews.average(:rate).to_f.round(1) %></td>
          <td><%= link_to stage.reviews.count, admin_reviews_path(stage_id: stage.id), class: "text-decoration-underline" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/stages/edit.html.erb
<div class="container">
  <h2 class='page-title'>公演情報編集</h2>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-sm-0 mx-auto">
      <%= render 'layouts/errors', obj: @stage %>
      <%= form_with model: @stage, url: admin_stage_path, local:true do |f| %>
        <div class="form-group">
          <%= f.label :name, "公演名", class: "badge" %><span class="required"></span>
          <%= f.text_field :name, :placeholder => "公演名", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :genre_id, "ジャンル", class: "badge" %><span class="required"></span><br />
          <%= f.collection_select :genre_id, Genre.all, :id, :name, :prompt => "-- 選択してください --", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :start_date, "公演開始日", class: "badge" %><span class="required"></span><br />
          <%= f.date_field :start_date %>
        </div>
        <div class="form-group">
          <%= f.label :end_date, "公演終了日", class: "badge" %><span class="required"></span><br />
          <%= f.date_field :end_date %>
        </div>
        <div class="form-group">
          <%= f.label :detail, "公演詳細", class: "badge" %>
          <%= f.text_area :detail, :rows => "5", :placeholder => "ここに詳細な内容を記述してください", class: "form-control" %>
        </div>
        <div class="form-group text-center mt-4">
          <%= f.submit "更新する", class: 'btn btn-dark mr-3 col-5 col-md-3' %>
          <%= link_to "キャンセル", admin_stage_path, class: 'btn btn-dark col-5 col-md-3' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/stages/index.html.erb
<div class="container">
  <% if params[:genre_id] %>
    <h2 class='page-title'>“<%= @genre.name %>”公演一覧</h2>
  <% else %>
    <h2 class='page-title'>公演一覧</h2>
  <% end %>
  <div class="row">
    <div class="col-md-10 mx-auto">
      <div class="text-center mb-4">
        <%= link_to "公演を新規登録する",new_admin_stage_path, class: "btn btn-dark px-3" %>
      </div>
      <%= render 'admin/stages/index', stages: @stages %>
    </div>
  </div>
  <div class="mt-3 d-flex justify-content-center"><%= paginate @stages %></div>
</div>

app/views/admin/stages/new.html.erb
<div class="container">
  <h2 class='page-title'>公演情報登録</h2>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-sm-0 mx-auto">
      <%= render 'layouts/errors', obj: @stage %>
      <%= form_with model: @stage, url: admin_stages_path, local:true do |f| %>
        <div class="form-group">
          <%= f.label :name, "公演名", class: "badge" %><span class="required"></span>
          <%= f.text_field :name, :placeholder => "公演名", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :genre_id, "ジャンル", class: "badge" %><span class="required"></span><br />
          <%= f.collection_select :genre_id, Genre.all, :id, :name, :prompt => "-- 選択してください --", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :start_date, "公演開始日", class: "badge" %><span class="required"></span><br />
          <%= f.date_field :start_date %>
        </div>
        <div class="form-group">
          <%= f.label :end_date, "公演終了日", class: "badge" %><span class="required"></span><br />
          <%= f.date_field :end_date %>
        </div>
        <div class="form-group">
          <%= f.label :introduction, "公演詳細", class: "badge" %>
          <%= f.text_area :introduction, :rows => "5", :placeholder => "ここに詳細な内容を記述してください", class: "form-control" %>
        </div>
        <div class="form-group text-center mt-4">
          <%= f.submit "新規登録", class: 'btn btn-dark' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/stages/show.html.erb
<div class="container">
  <div class="row px-3">
    <div class="col-md-8 mx-auto mt-4 bg-white p-4">
      <h4><strong><%= @stage.name %></strong></h4>
      <div class="mt-3">
        <%= @stage.start_date.strftime("%Y年%-m月%-d日") %>〜<%= @stage.end_date.strftime("%Y年%-m月%-d日") %>　<%= link_to @stage.genre.name, admin_stages_path(genre_id: @stage.genre.id), class: "badge" %>
      </div>
      <div class="d-flex align-items-center">
        <div id="star-rate-<%= @stage.id %>"></div>
        <div class="rating-score"><%= @stage.reviews.average(:rate).to_f.round(1) %></div>
        <%= link_to admin_reviews_path(stage_id: @stage.id) do %>
          <div>全<%= @stage.reviews.count %>件</div>
        <% end %>
      </div>
      <div class="mt-3">
        <p><%=simple_format(@stage.detail)%></p>
      </div>
    </div>
  </div>
    <div class="mt-5 text-center">
      <%= link_to "編集する", edit_admin_stage_path(@stage), class: "btn btn-dark px-4 mr-5" %>
      <%= link_to "削除する", admin_stage_path(@stage), method: :delete, class: "btn btn-outline-dark px-4", "data-confirm" => "本当に削除しますか？" %>
    </div>
</div>

<%= render 'public/stages/rate_average', stage: @stage %>