config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'public/users/sessions',
    registrations: 'public/users/registrations'
  }

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    resources :stages, except: [:destroy] do
      resource :bookmarks, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update] do
      member do
        get 'quit'
        patch 'withdraw'
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :reviews do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    get 'search' => 'stages#search'

    resources :contacts, only: [:new, :create]
    post 'contacts/confirm' => 'contacts#confirm'
    post 'contacts/back' => 'contacts#back'
    get 'contacts/done' => 'contacts#done'

    devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    end
  end

  # 以下管理者のルーティング
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :stages
    resources :users, only: [:index, :edit, :update]
    resources :reviews, only: [:index, :show, :edit, :update, :destroy]
    get 'search' => 'search#search'
    resources :contacts, only: [:index, :show]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :stage

  validates_uniqueness_of :stage_id, scope: :user_id
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review

  validates :content, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :subject, presence: true
  validates :message, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :review

  validates_uniqueness_of :review_id, scope: :user_id
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :stages
  validates :name, presence: true, uniqueness: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :stage
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :commented_users, through: :comments, source: :user
  validates :rate, presence: true
  validates :rate, numericality: {
      less_than_or_equal_to: 5,
      greater_than_or_equal_to: 0.5
   },
   if:  Proc.new { |a| a.rate.present? }

  def favorited_by?(user)
    favorites.where(user_id: user).exists?
  end

  def self.sort(selection)
    case selection
    when 'new'
      all.order(created_at: :DESC)
    when 'old'
      all.order(created_at: :ASC)
    when 'watched'
      all.order(date: :DESC)
    when 'watched_a'
      all.order(date: :ASC)
    when 'rate'
      all.order(rate: :DESC)
    when 'favorites'
      all.sort { |a, b| b.favorited_users.size <=> a.favorited_users.size }
    when 'comments'
      all.sort { |a, b| b.commented_users.size <=> a.commented_users.size }
    end
  end
end

app/models/stage.rb
class Stage < ApplicationRecord
  belongs_to :genre
  has_many :reviews, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :genre, :start_date, :end_date, presence: true
  validate :end_date_check

  def end_date_check
    errors.add(:end_date, "は公演開始日と同じ日または遅い日を選択してください") if start_date.present? && end_date.present? && self.start_date > self.end_date
  end

  def bookmarked_by?(user)
    bookmarks.where(user_id: user).exists?
  end

  def stage_id_and_name
    self.id.to_s + '. ' + self.name
  end

  scope :stages_now, -> { where("start_date <= ?", Date.today).where("end_date >= ?", Date.today) }
  scope :stages_coming, -> { where("start_date > ?", Date.today) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews
  has_many :bookmarks, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_reviews, through: :favorites, source: :review
  has_many :commented_reviews, through: :comments, source: :review
  validates :name, presence: true
  attachment :image
  validates :introduction, length: { maximum: 100 }

  # 退会ユーザーをログインさせない
  def active_for_authentication?
    super && (is_deleted == false)
  end

  def inactive_message
    "退会済みのアカウントです。"
  end

  # 自分がフォローされる側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when User
      user_path(resource)
    when Admin
      admin_reviews_path
    end
  end

  def after_sign_out_path_for(resource)
    case resource
    when :user
      root_path
    when :admin
      new_admin_session_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/search_helper.rb
module Admin::SearchHelper
end

app/helpers/admin/stages_helper.rb
module Admin::StagesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h5><%= pluralize(obj.errors.count, "件") %>のエラーが発生しました </h5>
  <ul>
    <% obj.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<p><%= link_to "ホーム", root_path, class: "border-right mr-2 pr-2" %><%= link_to "STAGE REVIEWについて", about_path, class: "border-right mr-2 pr-2" %><%= link_to "お問い合わせ", new_contact_path %></p>
<p>©️STAGE REVIEW</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-custom navbar-expand-lg navbar-light shadow fixed-top">
  <div class="container-xl">
    <a class="navbar-brand" href="/"><%= image_tag 'logo.png', size: "130x40" %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- 検索フォーム -->
      <div class="form-group my-2 my-md-0 ml-auto mr-3">
        <% if admin_signed_in? %>
          <%= form_with url: admin_search_path, method: :get, class: "form-inline", local: true do |f| %>
            <%= f.select 'search[model]', options_for_select({ "公演名" => "stage", "ユーザー名" => "user" }), class: "form-control col-6 col-sm-4"%>
            <%= f.text_field 'search[value]', class: "form-control col-10 col-sm-6" %>
            <%= button_tag type: "submit", class: "btn btn-dark col-2" do %>
              <i class="fas fa-search"></i>
            <% end %>
          <% end %>
        <% else %>
          <%= form_with url: search_path, method: :get, class: "form-inline", local: true do |f| %>
            <%= f.text_field :keyword, value: @keyword, placeholder: "公演名", class: "form-control col-10" %>
            <%= button_tag type: "submit", class: "btn btn-dark col-2" do %>
              <i class="fas fa-search"></i>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item mr-4"><%= link_to "公演一覧", stages_path, class: "nav-link" %></li>
          <li class="nav-item mr-4"><%= link_to "マイページ", user_path(current_user), class: "nav-link" %></li>
          <li class="nav-item mr-4"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
        <% elsif admin_signed_in? %>
          <li class="nav-item mr-4"><%= link_to "ユーザー", admin_users_path, class: "nav-link" %></li>
          <li class="nav-item mr-4"><%= link_to "公演", admin_stages_path, class: "nav-link" %></li>
          <li class="nav-item mr-4"><%= link_to "ジャンル", admin_genres_path, class: "nav-link" %></li>
          <li class="nav-item mr-4"><%= link_to "お問い合わせ", admin_contacts_path, class: "nav-link" %></li>
          <li class="nav-item mr-4"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %></li>
        <% else %>
          <li class="nav-item mr-4"><%= link_to "ABOUT", about_path, class: "nav-link" %></li>
          <li class="nav-item mr-4"><%= link_to "新規登録", new_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item mr-4"><%= link_to "ログイン", new_user_session_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_rate_form.html.erb
<!--星評価 stages/newで使用-->
<script>
    $('#rating-form').raty({
        starOn: "<%= asset_path('star-on.png') %>",
        starOff: "<%= asset_path('star-off.png') %>",
        starHalf: "<%= asset_path('star-half.png') %>",
        scoreName: 'review[rate]',
        half: true
    });
</script>

app/views/layouts/_rate_result.html.erb
<!--星評価 stages/showで使用-->
<script>
  $('#star-rate-<%= stage.id %>').empty();
    $('#star-rate-<%= stage.id %>').raty({
      starOn: "<%= asset_path('star-on.png') %>",
      starOff: "<%= asset_path('star-off.png') %>",
      starHalf: "<%= asset_path('star-half.png') %>",
      half: true,
      readOnly: true,
      score: <%= stage.reviews.average(:rate).to_f.round(1) %>,
      //平均点を算出し、round関数で切り上げ
    });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="演劇やステージのレビューを投稿できる機能を中心に、観劇の記録、観劇したい作品の備忘録、観客同士のコミュニケーションツールとしてご利用いただけるサイトです。">
    <%= favicon_link_tag('favicon.ico') %>
    <title>STAGE REVIEW</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header><%= render 'layouts/header' %></header>
    <p id="alert"><%= alert %></p>
    <%= yield %>
    <footer><%= render 'layouts/footer' %></footer>
  </body>
</html>