config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'public/users/sessions',
    registrations: 'public/users/registrations'
  }

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    resources :stages, except: [:destroy] do
      resource :bookmarks, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update] do
      member do
        get 'quit'
        patch 'withdraw'
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :reviews do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    get 'search' => 'stages#search'

    resources :contacts, only: [:new, :create]
    post 'contacts/confirm' => 'contacts#confirm'
    post 'contacts/back' => 'contacts#back'
    get 'contacts/done' => 'contacts#done'

    devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    end
  end

  # 以下管理者のルーティング
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :stages
    resources :users, only: [:index, :edit, :update]
    resources :reviews, only: [:index, :show, :edit, :update, :destroy]
    get 'search' => 'search#search'
    resources :contacts, only: [:index, :show]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews
  has_many :bookmarks, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_reviews, through: :favorites, source: :review
  has_many :commented_reviews, through: :comments, source: :review
  validates :name, presence: true
  attachment :image
  validates :introduction, length: { maximum: 100 }

  # 退会ユーザーをログインさせない
  def active_for_authentication?
    super && (is_deleted == false)
  end

  def inactive_message
    "退会済みのアカウントです。"
  end

  # 自分がフォローされる側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = User.all.page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:is_deleted)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_index.html.erb
<div class="table-responsive">
  <table class="table bg-white text-center" style="table-layout:fixed;">
    <thead class="thead-light">
      <tr>
        <th style="width:100px;">ユーザーID</th>
        <th style="width:200px;">ユーザーネーム</th>
        <th style="width:250px;">メールアドレス</th>
        <th style="width:150px;">ステータス</th>
        <th style="width:100px;">レビュー数</th>
      </tr>
    </thead>
    <tbody>
      <% users.each do |user| %>
        <tr>
          <td><%= user.id%></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td>
            <% if user.is_deleted %>
              <span class="text-muted"><strong>退会</strong></span>
            <% else %>
              <span class="text-success"><strong>有効</strong></span>
            <% end %>
            <%= link_to "編集", edit_admin_user_path(user), class: "btn btn-sm btn-dark ml-2" %>
          </td>
          <td><%= link_to user.reviews.count, admin_reviews_path(user_id: user.id), class: "text-decoration-underline" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/users/edit.html.erb
<div class="container">
  <h2 class='page-title'>ユーザー編集</h2>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-sm-0 mx-auto">
      <%= form_with model: @user, url: admin_user_path(@user), local:true do |f| %>
        <div class="form-group text-center">
          <label class="badge">ユーザーID</label><br />
          <%= @user.id %>
        </div>
         <div class="form-group text-center">
          <label class="badge">ユーザーネーム</label><br />
          <%= @user.name %>
        </div>
        <div class="form-group text-center">
          <%= f.label :is_deleted, "会員ステータス", class: "badge" %><br />
          <%= f.radio_button :is_deleted, false, class: "text-secondary" %>
          <%= f.label :is_deleted, '有効', value: false, class: "radio_btn mr-3" %>
          <%= f.radio_button :is_deleted, true %>
          <%= f.label :is_deleted, '退会', value: true, class: "radio_btn" %>
        </div>
        <div class="form-group text-center mt-4">
          <%= f.submit "更新する", class: 'btn btn-dark mr-3 col-5 col-md-3' %>
          <%= link_to "キャンセル", admin_users_path, class: 'btn btn-dark col-5 col-md-3' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <h2 class='page-title'>ユーザー一覧</h2>
  <div class="row">
    <div class="col-md-10 mx-auto">
      <%= render 'admin/users/index', users: @users %>
    </div>
  </div>
  <div class="mt-3 d-flex justify-content-center"><%= paginate @users %></div>
</div>